# Generated by Django 6.0.4 on 2026-04-10 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anio_estreno', models.IntegerField()),
                ('genero', models.CharField(choices=[('accion', 'Acción'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('ciencia_ficcion', 'Ciencia Ficción'), ('animacion', 'Animación'), ('romance', 'Romance'), ('thriller', 'Thriller')], max_length=50)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='gestion.director')),
            ],
        ),
    ]
